import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { Session } from "next-auth";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session;
}>) {
  return (
    <html lang="en">
      <Providers session={session}>
        <body>{children}</body>
      </Providers>
    </html>
  );
}
