import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { Session } from "next-auth";
import AppShell from "./app-shell";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <Providers>
        <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        />
      </head>
        <body>
        <AppShell />
        {children}
        </body>
      </Providers>
    </html>
  );
}
