FROM node:20-bookworm

WORKDIR /app

COPY apps/runner/package.json ./
RUN npm install typescript
COPY apps/runner/tsconfig.json ./
RUN npm install

COPY apps/runner/src ./src

CMD ["npm", "run", "dev"]
